name: store_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.1
  image_picker: ^1.0.5
  cupertino_icons: ^1.0.2
  sign_in_button: ^3.0.0
  firebase_auth: ^5.4.0
  geolocator: ^13.0.2
  fluttertoast: ^8.2.10
  flutter_image_compress: ^2.1.0
  path: ^1.8.3
  intl: ^0.19.0
  lottie: ^2.7.0
  rename: ^3.0.2
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  particles_flutter: ^0.1.4
  video_player: ^2.8.2
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  timeline_tile: ^2.0.0
  timeago: ^3.7.0
  path_provider: ^2.1.2
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  http: ^1.2.2
  model_viewer_plus: ^1.7.0
  url_launcher: ^6.2.4
  mime: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0
  flutter_lints: ^5.0.0

icons_launcher:
  image_path: 'assets/icon/icon.png'
  platforms:
    android:
      adaptive_background_color: '#ffffff'
      adaptive_background_image: 'assets/icon/icon.png'
      adaptive_foreground_image: 'assets/icon/icon.png'
      adaptive_round_image: 'assets/icon/icon.png'
      adaptive_monochrome_image: 'assets/icon/icon.png'
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icon/
